### PR TITLE
Add command to show versions for a project

### PR DESCRIPTION
**Pull request by kamilwaz**
It adds `jira versions` that list versions for a project. The command takes the same arguments as `jira components`.

### CODE REVIEW

**Comment by pkulev** [comment]
@coryb @ldelossa @mikepea bump please

**Review by georgettica — APPROVED** [review]
Looks ok, should test and see it works as expected.

Also maybe adding a test for this would help speed it up

**Comment by kamilwaz** [comment]
I tested it locally and it worked as expected. I can add a test but I'm not sure where - should it be added to `test` or `_t` (or both)? Is there any existing test that I can use as template?

**Comment by pkulev** [comment]
👍 🤣

**Pull request closed without merging**
