### PR TITLE
Remove (possible) infinite loop from CmdLogin.

### PR DESCRIPTION
**Pull request by seanblong**
Couldn't determine original intention of loop within `CmdLogin`, but ran into an issue locally where a cron job that ran the login command inadvertently got stuck in a failure loop where it continued to make bad requests to the Jira server.

### CODE REVIEW

**Comment by seanblong** [comment]
I believe this also addresses the reported issue: https://github.com/go-jira/jira/issues/345

**Comment by georgettica** [comment]
yeah! this looks great!

please add me as a reviewer and I will approve

**Comment by catskul** [comment]
Any reason this isn't merged?

**Comment by georgettica** [comment]
Not really, just lost touch of the project.
Thanks for checking on it.

I'll take a second look and merge when donr

**Comment by catskul** [comment]
Tested this one locally and appears to work correctly, and resolves loop as I saw it as well.

**Review by georgettica — APPROVED** [review]

**Comment by georgettica** [comment]
seems I don't have the power yet to approve (although I am in the list?)

**Comment by catskul** [comment]
Thanks for attempting! maybe we can get @ldelossa or @mikepea to weigh in and/or give you merging rights.

**Comment by georgettica** [comment]
🤞

**Comment by catskul** [comment]
Got a response from @mikepea https://twitter.com/mikepea/status/1463942769097904128 though it seems  he might not be comfortable approving new maitainers because he's not been involved for a while.

**Comment by georgettica** [comment]
Might be worth mentioning here that I was added to some extent as a maintainer
https://github.com/go-jira/jira/pull/426

**Pull request merged**
