### PR TITLE
Use accountId parameter for GDPR compliant API requests

### PR DESCRIPTION
**Pull request by pcockwell**
Adds `account-id` parameter to config parsing
Uses `accountId` parameter instead of `user` or `name` for `watch`, and `assign` issue commands

I have tested the functionality and can confirm the functionality acts as expected. This being said, I am relatively new to go, and have not gone through the trouble of figuring out how to run the automated tests, or even which tests need to be modified given these changes. Please feel free to advise.

This PR should fix issue https://github.com/go-jira/jira/issues/314

Thanks

### CODE REVIEW

**Comment by pcockwell** [comment]
The newest commit also modifies the output templates to use the `displayName` attribute of the `assignee` or `reporter` instead of the `name` attribute.

**Comment by Line-Noise** [comment]
This is working for me so far. Thanks!

**Comment by pcockwell** [comment]
The newest commit also modifies the output templates to use the `displayName` attribute of the `author` instead of the `name` attribute.

**Comment by coryb** [comment]
Hey, thanks for the PR!  Not sure how to proceed with this, unfortunately, we cannot merge as-is.  This is super frustrating that Atlassian has broken their APIs while not bothering to change the API versions.  One major issue is that this change is only for jira-cloud, but this tool is used a bunch with corporate on-premises Jira installs, so we will need to figure out some sort of compatibility.

We can usually auto-detect jira-cloud since it uses atlassian.net hostnames, but ideally, we would be able to interrogate a Jira API to get information about how the client needs to behave, not sure if something like this exists for Jira.

Also ideally we would be able to figure out what the `account-id` property should be from the login information without having yet another identification property in the config file.  

If anyone has a lead on any of these topics I would appreciate the help.  I think this will require some research to figure out how to solve the compatibility issues, and research takes time which I am very short on these days.

**Comment by TheKevJames** [comment]
> We can usually auto-detect jira-cloud since it uses atlassian.net hostnames, but ideally, we would be able to interrogate a Jira API to get information about how the client needs to behave, not sure if something like this exists for Jira.

I think the "right" way to do this would involve having Jira do things differently in their API. As that idea is probably a non-starter, maybe we could introduce a config option? I imagine we would introduce an `enterprise` argument in the configuration yaml and perhaps fallback to using auto-detection logic if it is unset. For example, the following psuedo-code, which is admittedly a bit of a kludge, could do the trick:
```python
if 'enterprise' not in config:
    # if the user has not given us a hint, do our best to auto-detect via hostname
    config['enterprise'] = bool('atlassian.net' not in config['endpoint'])

use_account_id = not bool(config['enterprise'])
```

> Also ideally we would be able to figure out what the `account-id` property should be from the login information without having yet another identification property in the config file.

This seems possible in principle, since in the worst case we could make a request to their API to find a ticket with `assignee=currentUser()`. I don't know much about the design of this library and whether needing to do this API request would be reasonable design; I also assume its likely that there's a route for this purpose rather than needing to create a hack like that.

> we cannot merge as-is

Totally understand this -- unfortunately, that puts those of us using `jira-cloud` a bit out in the rain. Is there some minimum amount of work we could do to at least unblock those users in the short term? Not sure on this libraries opinion on things like this, but would eg. adding the `enterprise` and `account-id` flags to the config and deprecating them once ~the Jira API gets its act together~ we figure out a stable auto-detection mechanism be reasonable?

**Comment by coryb** [comment]
Closing this issue since we merged #317

**Pull request closed without merging**
