### PR TITLE
use reporter.id instead of reporter.name in templates

### PR DESCRIPTION
**Pull request by bradym**
I ran into the issue in #333 earlier and was able to get around the issue editing the template. I've made those changes in this PR so they'll be in the default templates.

This fix currently requires setting overrides.reporter to your user id. I welcome any input if this is not the desired approach to fix this.

I believe his should also address #335 and #342.

### CODE REVIEW

**Comment by jtomaszewski** [comment]
Just a small comment, this and the gdpr changes will require us to use integer IDs instead of nicknames in the templates (`1234` instead of `jtomaszewski`), correct? 

It's a pity, but I guess we'll have to go with such workaround for now. Better this than not working at all.

I guess maybe we could somehow parse all the users using go jira api, and then find a user ID by their name? That's definitely a tougher thing to do, not sure yet how I'd start tackling it even. I'd vote for merging this and maybe making that improvement later as a separate PR.

**Comment by endorama** [comment]
> Other option: maybe we could somehow parse all the users using go jira api, and then find a user ID by their name? That's definitely a tougher thing to do, not sure yet how I'd start tackling it even. I'd vote for merging this and maybe making that improvement later as a separate PR.

Searching for some workarounds I found [this answer](https://community.atlassian.com/t5/Confluence-questions/Get-user-account-ID-via-API-from-email-username/qaq-p/1197704) from an Atlassian member:

> Currently, I believe that the fastest way to acquire such userIDs is by exporting the user list of your instance. [...]

Exporting the list requires admin rights, so I don't think this is feasible.

> After the domains are verified (if you needed to verify them), we can use our REST API endpoints to get the necessary user info. [...]

The endpoint mentioned is [this one](https://developer.atlassian.com/cloud/admin/organization/rest/#api-orgs-orgId-users-get). Maybe would be possible to get all users and cache the result somewhere providing some helper to convert usernames into ids.

**Comment by ldelossa** [comment]
@bradym please look at my latest comment on #333 
Can you try latest HEAD and see if template issue still exists?

If so mapping it to "Login" for the email, or mapping it to "id" like you are stating should fix the issue with templates.
the general "username" param not supported issue should be gone regardless.

**Comment by ldelossa** [comment]
BTW I think the "friendliest" mapping would be going from "Login" -> "DisplayName" which is supported after GDRP.

**Comment by bradym** [comment]
@ldelossa I haven't been able to test this, when I run `go get github.com/go-jira/jira/cmd/jira` as mentioned in the README I get the following

```
$ go get github.com/go-jira/jira/cmd/jira
# github.com/go-jira/jira/jiracli
go/src/github.com/go-jira/jira/jiracli/usage.go:158:45: cannot use app (type *"gopkg.in/alecthomas/kingpin.v2".Application) as type *"github.com/coryb/kingpeon/vendor/gopkg.in/alecthomas/kingpin.v2".Application in argument to kingpeon.RegisterDynamicCommandsWithRunner
```

**Comment by ldelossa** [comment]
Can you try clearing tour go cache? 

https://golang.org/cmd/go/#hdr-Remove_object_files_and_cached_files

**Comment by endorama** [comment]
@ldelossa I'm experiencing the same. I tried 

```
$ go clean -x -i -r github.com/go-jira/jira/cmd/jira
```
and 
```
$ go clean -x -i -r github.com/go-jira/jira...
```
but the error keep showing up.

**Comment by ldelossa** [comment]
@bradym  looks like you need to use it like this:

GO111MODULE=on go get github.com/go-jira/jira/cmd/jira

something strange is going on with importing kingping. not quite sure what yet.

**Comment by ldelossa** [comment]
@bradym for the sake of pushing this pr forward, does simply removing the "reporter" field remove the issue?

**Comment by bradym** [comment]
@ldelossa My apologies for such a slow response. I just tested in version 1.0.26 without any custom templates and removing the reporter field does work. Here's the yaml structure that worked:

```
fields:
  project:
    key: TEST 
  issuetype:
    name: Task
  summary: >-
    Test issue
  priority: # Values: P0, P1, P2, P3, P4, Major, Minor, Critical, Trivial, Blocker, 
    name: 
  description: |~
    This is a test issue
  assignee:
    name: 
```

**Comment by bradym** [comment]
Closing since the latest version works without this.

**Pull request closed without merging**
