### PR TITLE
georgettica/take ownership of pr 306

### PR DESCRIPTION
**Pull request by georgettica**
related to #306
as it fixes the reviews requested

### CODE REVIEW

**Comment by georgettica** [comment]
@miguelbernadi can you LGTM this?

Our team is plann

**Comment by miguelbernadi** [comment]
@georgettica I'm not a maintainer of this project just another user. I have no official powers here, sorry. 

OTOH, Thanks for picking it up. Seems decent but I'd have to take a deeper look at the YAML cleaning logic, I didn't follow it right away.

**Comment by georgettica** [comment]
I feel.this code is missing the tank templating I want.

I gave it a yaml file and it spat out the same thing in JIRA land

I thought this would be good enough as a first pass but I am not sure..

**Comment by georgettica** [comment]
@coryb is this PR in the right track?
If so what should I change to make this merge worthy?

**Review by ldelossa — APPROVED** [review]

**Pull request merged**
